services:
  - type: web
    name: financeiro
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npx prisma generate && npm run build:backend
    startCommand: npx prisma migrate deploy && node dist/backend/server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: CORS_ORIGIN
        sync: false
